import type { Role, Permission } from "../types";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  OWNER: [
    "products.view",
    "products.create",
    "products.edit",
    "products.delete",
    "inventory.view",
    "inventory.adjust",
    "inventory.transfer",
    "sales.view",
    "sales.create",
    "sales.cancel",
    "sales.refund",
    "purchases.view",
    "purchases.create",
    "purchases.receive",
    "purchases.cancel",
    "settings.view",
    "settings.edit",
    "users.view",
    "users.create",
    "users.edit",
    "users.delete",
  ],
  ADMIN: [
    "products.view",
    "products.create",
    "products.edit",
    "products.delete",
    "inventory.view",
    "inventory.adjust",
    "inventory.transfer",
    "sales.view",
    "sales.create",
    "sales.cancel",
    "sales.refund",
    "purchases.view",
    "purchases.create",
    "purchases.receive",
    "purchases.cancel",
    "settings.view",
    "settings.edit",
    "users.view",
    "users.create",
    "users.edit",
  ],
  WAREHOUSE: [
    "products.view",
    "inventory.view",
    "inventory.adjust",
    "inventory.transfer",
    "purchases.view",
    "purchases.receive",
  ],
  PURCHASING: [
    "products.view",
    "inventory.view",
    "purchases.view",
    "purchases.create",
    "purchases.receive",
    "purchases.cancel",
  ],
};
